name: Manage bucket & upload script

on:
  push:
    branches: [ "main", "dev" ]

  workflow_dispatch:


permissions:
  contents: read
  id-token: write

env:
  BUCKET_NAME: sparkresultsjjj${{ github.ref_name }}
  AWS_REGION: eu-west-3


jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ env.AWS_REGION }}"
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}  # this will be the ARN of the role you created in the "Creating a Role for deployment" step.
          role-session-name: GithubActions-S3
          mask-aws-account-id: true
      - name: Create bucket if not exists
        run: |   
          if aws s3api head-bucket --bucket "${{ env.BUCKET_NAME}}" 2>/dev/null; then
            echo "Bucket exists"
          else
            echo "Creating bucket"
            aws s3api create-bucket \
              --bucket "${{ env.BUCKET_NAME}}" \
              --region "${{ env.AWS_REGION }}" \
              --create-bucket-configuration LocationConstraint="${{ env.AWS_REGION }}" \
            
            aws s3api put-bucket-policy --bucket "${{ env.BUCKET_NAME}}" --policy '{
            "Version":"2012-10-17",
            "Statement":[{"Sid":"AllowEMRAccess","Effect":"Allow","Principal": {arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}},"Action":["s3:GetObject","s3:PutObject","s3:ListBucket"],"Resource":["arn:aws:s3:::'"${{ env.BUCKET_NAME}}"'","arn:aws:s3:::'"${{ env.BUCKET_NAME}}"'/*"]}]}'
          
            aws s3api put-bucket-versioning \
              --bucket "${{ env.BUCKET_NAME }}" \
              --versioning-configuration Status=Enabled

          fi


  upload-script:
    runs-on: ubuntu-latest
    needs: create-bucket
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ env.AWS_REGION }}"
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}  # this will be the ARN of the role you created in the "Creating a Role for deployment" step.
          role-session-name: GithubActions-S3
          mask-aws-account-id: true
      - name: Upload script to S3
        run: |
          echo "Upload script.py to the bucket/src"
          aws s3 cp code/script.py s3://${{ env.BUCKET_NAME}}/src/ --region ${{ env.AWS_REGION }}

